version: '3.3'
services:
    ffmpeg-nvenc:
        devices:
            - /dev/nvidia-caps
            - /dev/nvidia0
            - /dev/nvidiactl
            - /dev/nvidia-modeset
            - /dev/nvidia-uvm
            - /dev/nvidia-uvm-tools
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
            - /volumes_etc:/etc/ffplayout:rw
            - /volumes_db:/usr/share/ffplayout:rw
            - /volumes_lib:/var/lib/ffplayout:rw
        ports:
            - '8686:8787'
        privileged: true
        image: ffmpeg-nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
        command:
            - '/usr/sbin/init'
